apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: promtail
  namespace: loki
spec:
  releaseName: promtail
  chart:
    repository: https://grafana.github.io/loki/charts/
    name: promtail
    version: 2.0.1
