apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  releaseName: prometheus
  chart:
    repository: https://prometheus-community.github.io/helm-charts/
    name: prometheus
    version: 13.0.0
  values:
    alertmanager.persistentVolume.storageClass: "gp2"
    server.persistentVolume.storageClass: "gp2"