apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  releaseName: grafana
  chart:
    repository: https://grafana.github.io/helm-charts/
    name: grafana
    version: ~6.1.14
  values:
    persistence.storageClassName: "gp2"
    persistence.enabled: true
    adminPassword: "tempPassword"
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server.prometheus.svc.cluster.local
          access: proxy
          isDefault: true
