apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx/
    name: ingress-nginx
    version: 3.15.2
  values:
    controller:
      kind: DaemonSet
      config:
        use-forwarded-headers: "true"
      metrics:
        enabled: true
      service:
        annotations:
          prometheus.io/scrape: "true"

        internal:
          enabled: true
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
            service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
            service.beta.kubernetes.io/aws-load-balancer-type: nlb
            prometheus.io/scrape: "true"
          externalTrafficPolicy: Local
    
