apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  releaseName: podinfo
  chart:
    repository: https://stefanprodan.github.io/podinfo/
    name: podinfo
    version: 5.1.1
  values:
    replicaCount: 2
