apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: podinfo-cert
  namespace: projectcontour
spec:
  secretName: podinfo-ssl
  commonName: "podinfo.questdev.xyz"
  dnsNames:
  - "podinfo.questdev.xyz"
  issuerRef:
    name: lets-encrypt-issuer
    kind: ClusterIssuer
